import { useEffect, useMemo, useState } from "react";
import api, { formatINR } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

const STATUSES = ["Present", "Half Day", "Absent"];
const short = { Present: "P", "Half Day": "H", Absent: "A" };
const statusClass = { Present: "bg-emerald-100 text-emerald-800 border-emerald-200", "Half Day": "bg-amber-100 text-amber-800 border-amber-200", Absent: "bg-rose-100 text-rose-800 border-rose-200" };

export default function Attendance() {
  const today = new Date().toISOString().slice(0, 10);
  const [date, setDate] = useState(today); const [month, setMonth] = useState(today.slice(0, 7)); const [firmId, setFirmId] = useState("all");
  const [employeeId, setEmployeeId] = useState("all");
  const [daily, setDaily] = useState(null); const [summary, setSummary] = useState(null); const [firms, setFirms] = useState([]); const [saving, setSaving] = useState({});
  const params = firmId === "all" ? {} : { firm_id: firmId };
  const load = async () => { const [day, monthSummary, firmList] = await Promise.all([api.get("/attendance", { params: { date, ...params } }), api.get("/attendance/summary", { params: { month, ...params } }), api.get("/firms")]); setDaily(day.data); setSummary(monthSummary.data); setFirms(firmList.data); };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load(); }, [date, month, firmId]);
  const days = useMemo(() => { const [year, m] = month.split("-").map(Number); return Array.from({ length: new Date(year, m, 0).getDate() }, (_, index) => `${month}-${String(index + 1).padStart(2, "0")}`); }, [month]);
  const save = async (employeeId, status) => { setSaving((v) => ({ ...v, [employeeId]: true })); try { await api.put("/attendance", { employee_id: employeeId, date, status }); toast.success("Attendance saved"); await load(); } catch (e) { toast.error(e.response?.data?.detail || "Could not save attendance"); } finally { setSaving((v) => ({ ...v, [employeeId]: false })); } };
  const selectedEmployees = (summary?.employees || []).filter((employee) => employeeId === "all" || employee.employee_id === employeeId);
  const selectedDailyEmployees = (daily?.employees || []).filter((employee) => employeeId === "all" || employee.employee_id === employeeId);
  const totals = selectedEmployees.reduce((acc, employee) => ({ present: acc.present + employee.present_days, half: acc.half + employee.half_days, absent: acc.absent + employee.absent_days, salary: acc.salary + employee.calculated_salary }), { present: 0, half: 0, absent: 0, salary: 0 });
  return <div className="p-8 max-w-[1800px] mx-auto">
    <div className="flex items-end justify-between mb-8 pb-6 border-b border-zinc-200"><div><div className="text-xs font-mono-num uppercase tracking-widest text-zinc-500 mb-2">04 · Workforce</div><h1 className="font-display text-4xl font-medium tracking-tight">Attendance Management</h1><p className="text-sm text-zinc-500 mt-1">Day-wise employee attendance, monthly payroll days, and salary calculation in one workspace.</p></div><div className="flex gap-2"><input type="month" value={month} onChange={(e) => { setMonth(e.target.value); if (!date.startsWith(e.target.value)) setDate(`${e.target.value}-01`); }} className="h-9 border border-zinc-300 px-3 font-mono-num text-sm" />{firms.length > 0 && <select value={firmId} onChange={(e) => { setFirmId(e.target.value); setEmployeeId("all"); }} className="h-9 border border-zinc-300 px-3 text-sm bg-white"><option value="all">All firms</option>{firms.map((firm) => <option key={firm.firm_id} value={firm.firm_id}>{firm.name}</option>)}</select>}<select value={employeeId} onChange={(e) => setEmployeeId(e.target.value)} className="h-9 border border-zinc-300 px-3 text-sm bg-white"><option value="all">All employees</option>{(summary?.employees || []).map((employee) => <option key={employee.employee_id} value={employee.employee_id}>{employee.name}</option>)}</select></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">{[["Present marks", totals.present, "text-emerald-700"],["Half-day marks", totals.half, "text-amber-700"],["Absent marks", totals.absent, "text-rose-700"],["Attendance salary", formatINR(totals.salary), "text-zinc-950"]].map(([label, value, color]) => <div key={label} className="border border-zinc-200 bg-white p-5"><div className="text-[10px] uppercase tracking-widest text-zinc-500 font-mono-num">{label}</div><div className={`font-mono-num text-2xl mt-2 ${color}`}>{value}</div><div className="text-xs text-zinc-500 mt-1">{month}</div></div>)}</div>
    {employeeId !== "all" && selectedEmployees[0] && <div className="border border-zinc-950 bg-zinc-950 text-white p-5 mb-8 flex justify-between"><div><div className="text-[10px] uppercase tracking-widest text-zinc-400 font-mono-num">Selected employee</div><div className="font-display text-2xl mt-1">{selectedEmployees[0].name}</div><div className="text-sm text-zinc-400 mt-1">Daily rate: {formatINR(selectedEmployees[0].base_salary / summary.days_in_month)} · {summary.days_in_month} calendar days</div></div><div className="text-right"><div className="text-[10px] uppercase tracking-widest text-zinc-400 font-mono-num">Salary from marked days</div><div className="font-mono-num text-3xl mt-1">{formatINR(selectedEmployees[0].calculated_salary)}</div><div className="text-sm text-zinc-400 mt-1">{selectedEmployees[0].payable_days} paid days</div></div></div>}
    <section className="border border-zinc-200 bg-white mb-8"><div className="p-5 border-b border-zinc-200 flex items-center justify-between"><div><div className="text-[10px] font-mono-num uppercase tracking-widest text-zinc-500">Daily register</div><h2 className="font-display text-xl mt-1">Mark attendance for each employee</h2></div><input type="date" value={date} min={`${month}-01`} max={`${month}-${String(days.length).padStart(2, "0")}`} onChange={(e) => setDate(e.target.value)} className="h-9 border border-zinc-300 px-3 font-mono-num text-sm" /></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-[10px] font-mono-num uppercase tracking-widest text-zinc-500"><th className="text-left py-3 px-4">Employee</th><th className="text-left py-3 px-4">Role</th><th className="text-right py-3 px-4">Monthly salary</th><th className="text-left py-3 px-4">Status on {date}</th></tr></thead><tbody>{selectedDailyEmployees.map((employee) => <tr key={employee.employee_id} className="border-b border-zinc-100"><td className="py-3 px-4 font-medium">{employee.name}</td><td className="py-3 px-4 text-zinc-500">{employee.role_title || "—"}</td><td className="py-3 px-4 text-right font-mono-num">{formatINR(employee.base_salary)}</td><td className="py-3 px-4"><div className="flex gap-2">{STATUSES.map((status) => <Button key={status} disabled={saving[employee.employee_id]} onClick={() => save(employee.employee_id, status)} variant="outline" className={`h-8 rounded-none text-xs ${employee.attendance?.status === status ? statusClass[status] : "border-zinc-200"}`}>{status}</Button>)}</div></td></tr>)}</tbody></table></div></section>
    <section className="border border-zinc-200 bg-white"><div className="p-5 border-b border-zinc-200"><div className="text-[10px] font-mono-num uppercase tracking-widest text-zinc-500">Month grid · {month}</div><h2 className="font-display text-xl mt-1">Employee-wise, day-wise attendance</h2><div className="flex gap-3 mt-3 text-xs"><span className="border px-2 py-1 bg-emerald-100 text-emerald-800">P = Present</span><span className="border px-2 py-1 bg-amber-100 text-amber-800">H = Half Day</span><span className="border px-2 py-1 bg-rose-100 text-rose-800">A = Absent</span><span className="text-zinc-500 py-1">Blank means not marked yet.</span></div></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b text-[10px] font-mono-num uppercase tracking-widest text-zinc-500"><th className="sticky left-0 z-10 bg-white text-left py-3 px-4 min-w-40">Employee</th>{days.map((day) => <th key={day} className="text-center px-2 min-w-9">{day.slice(-2)}</th>)}<th className="text-right px-3 min-w-16">P</th><th className="text-right px-3 min-w-16">H</th><th className="text-right px-3 min-w-16">A</th><th className="text-right px-3 min-w-20">Paid days</th><th className="text-right px-4 min-w-28">Salary</th></tr></thead><tbody>{selectedEmployees.map((employee) => { const marks = Object.fromEntries(employee.records.map((record) => [record.date, record.status])); return <tr key={employee.employee_id} className="border-b border-zinc-100"><td className="sticky left-0 z-10 bg-white py-3 px-4 font-medium">{employee.name}</td>{days.map((day) => <td key={day} className="text-center px-1"><span title={`${day}: ${marks[day] || "Not marked"}`} className={`inline-flex w-6 h-6 items-center justify-center border font-mono-num ${marks[day] ? statusClass[marks[day]] : "border-zinc-100 text-zinc-300"}`}>{marks[day] ? short[marks[day]] : "—"}</span></td>)}<td className="text-right px-3 font-mono-num text-emerald-700">{employee.present_days}</td><td className="text-right px-3 font-mono-num text-amber-700">{employee.half_days}</td><td className="text-right px-3 font-mono-num text-rose-700">{employee.absent_days}</td><td className="text-right px-3 font-mono-num">{employee.payable_days}</td><td className="text-right px-4 font-mono-num font-medium">{formatINR(employee.calculated_salary)}</td></tr>; })}</tbody></table></div></section>
  </div>;
}
